# -*- coding: utf-8 -*-
"""etl-data-pipeline2500292020.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jrRYtIqkFkLa_lHS9xl5Z4UpFhD-8CQg
"""

!pip install pandas sqlalchemy psycopg2-binary

import pandas as pd
import os

# URLs raw de GitHub (Reemplazar 'TU_USUARIO' y 'TU_REPO')
url_ventas = 'https://raw.githubusercontent.com/IvanMoreno-utec/etl-data-pipeline2500292020/refs/heads/main/data/raw/C_ventas.csv'
url_pagos = 'https://raw.githubusercontent.com/IvanMoreno-utec/etl-data-pipeline2500292020/refs/heads/main/data/raw/C_pagos.csv'
url_clientes = 'https://raw.githubusercontent.com/IvanMoreno-utec/etl-data-pipeline2500292020/refs/heads/main/data/raw/C_clientes.csv'

df_ventas = pd.read_csv(url_ventas)
df_pagos = pd.read_csv(url_pagos)
df_clientes = pd.read_csv(url_clientes)

#Limpiar los datos
df_ventas['total'] = pd.to_numeric(df_ventas['total'].astype(str).str.replace('USD', '', regex=False).str.strip(), errors='coerce')
df_ventas['fecha'] = pd.to_datetime(df_ventas['fecha'], errors='coerce')

df_pagos['monto_pagado'] = pd.to_numeric(df_pagos['monto_pagado'].astype(str).str.replace('$', '', regex=False).str.strip(), errors='coerce')
df_pagos['metodo'] = df_pagos['metodo'].astype(str).str.strip()

#Separar datos curated y rejects por archivo
mask_ventas = df_ventas.isnull().any(axis=1)
curated_ventas = df_ventas[~mask_ventas]
rejects_ventas = df_ventas[mask_ventas]

mask_pagos = df_pagos.isnull().any(axis=1)
curated_pagos = df_pagos[~mask_pagos]
rejects_pagos = df_pagos[mask_pagos]

mask_clientes = df_clientes.isnull().any(axis=1)
curated_clientes = df_clientes[~mask_clientes]
rejects_clientes = df_clientes[mask_clientes]

#Crear estructura y guardar
base_dir = "etl-data-pipeline2500292020"
os.makedirs(f"{base_dir}/data/raw", exist_ok=True)
os.makedirs(f"{base_dir}/data/curated", exist_ok=True)
os.makedirs(f"{base_dir}/data/rejects", exist_ok=True)
os.makedirs(f"{base_dir}/notebooks", exist_ok=True)
os.makedirs(f"{base_dir}/scripts", exist_ok=True)
os.makedirs(f"{base_dir}/docs", exist_ok=True)

curated_ventas.to_csv(f'{base_dir}/data/curated/curated_ventas.csv', index=False)
rejects_ventas.to_csv(f'{base_dir}/data/rejects/rejects_ventas.csv', index=False)

curated_pagos.to_csv(f'{base_dir}/data/curated/curated_pagos.csv', index=False)
rejects_pagos.to_csv(f'{base_dir}/data/rejects/rejects_pagos.csv', index=False)

curated_clientes.to_csv(f'{base_dir}/data/curated/curated_clientes.csv', index=False)
rejects_clientes.to_csv(f'{base_dir}/data/rejects/rejects_clientes.csv', index=False)

from sqlalchemy import create_engine

#Cargar los datos en PostgreSQL
DATABASE_URL = "postgresql://etl_user:681fGSt7lSalqt4FNlgn2O1y3WvqJqMj@dpg-d6quak0gjchc73en7ksg-a.oregon-postgres.render.com/etl_seguros_qdd3"
engine = create_engine(DATABASE_URL)

curated_ventas.to_sql('curated_ventas', engine, if_exists='replace', index=False)
rejects_ventas.to_sql('rejects_ventas', engine, if_exists='replace', index=False)

curated_pagos.to_sql('curated_pagos', engine, if_exists='replace', index=False)
rejects_pagos.to_sql('rejects_pagos', engine, if_exists='replace', index=False)

curated_clientes.to_sql('curated_clientes', engine, if_exists='replace', index=False)
rejects_clientes.to_sql('rejects_clientes', engine, if_exists='replace', index=False)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd etl-data-pipeline2500292020
# 
# echo -e "pandas\nsqlalchemy\npsycopg2-binary" > requeriments.txt
# touch README.md
# 
# git config --global user.email "2500292020@mail.utec.edu.sv"
# git config --global user.name "IvanMoreno-utec"
# 
# # Re-inicializar para asegurar limpieza
# rm -rf .git
# git init
# git add .
# git commit -m "Pipeline ETL: separación de curated y rejects por archivo"
# git branch -M main
# 
# # Usamos el flag --force para resolver el conflicto de historias distintas
# git remote add origin https://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@github.com/IvanMoreno-utec/etl-data-pipeline2500292020.git
# git push -u origin main --force

